// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Docker 环境变量已注入，无需 dotenv 加载 .env 文件
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "",
  },
});
